# Generated by Django 6.1 on 2026-09-02 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField()),
                ('participant_id', models.UUIDField()),
                ('metric_ref', models.UUIDField()),
                ('input_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('input_unit_ref', models.UUIDField()),
                ('norm_binding_id', models.UUIDField()),
                ('population_id', models.UUIDField()),
                ('norm_mean', models.DecimalField(decimal_places=3, max_digits=10)),
                ('norm_sd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('norm_min', models.DecimalField(decimal_places=3, max_digits=10)),
                ('norm_max', models.DecimalField(decimal_places=3, max_digits=10)),
                ('norm_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('norm_z_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('norm_t_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('norm_label_code', models.CharField(choices=[('EXCELLENT', 'Çok İyi'), ('GOOD', 'İyi'), ('AVERAGE', 'Ortalama'), ('POOR', 'Zayıf'), ('VERY_POOR', 'Çok Zayıf')], max_length=20)),
                ('norm_label', models.CharField(blank=True, max_length=50)),
                ('comparison_code', models.CharField(choices=[('ABOVE_AVERAGE', 'Ortalamanın Üzerinde'), ('BELOW_AVERAGE', 'Ortalamanın Altında'), ('EQUAL', 'Ortalamaya Eşit')], max_length=20)),
                ('comparison_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Yayınlandı'), ('RETRACTED', 'Geri Çekildi')], default='PUBLISHED', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'norm_normresult',
                'indexes': [models.Index(fields=['batch_id', 'participant_id', 'metric_ref'], name='norm_normre_batch_i_ce7df2_idx')],
            },
        ),
    ]
