# Generated by Django 6.1 on 2026-09-02 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.JSONField(verbose_name='Ad (9 dil)')),
                ('participation_mode', models.CharField(choices=[('INDIVIDUAL', 'Bireysel'), ('GROUP', 'Grup'), ('MIXED', 'Karma')], max_length=20)),
                ('lifecycle_status', models.CharField(choices=[('DRAFT', 'Taslak'), ('REVIEW', 'İncelemede'), ('SCHEDULED', 'Planlandı'), ('LOCKED', 'Kilitli'), ('EXPIRED', 'Zamanı Geçti'), ('CANCELLED', 'İptal Edildi')], db_index=True, default='DRAFT', max_length=20)),
                ('optimistic_revision', models.IntegerField(default=1)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'planning_testsession',
            },
        ),
        migrations.CreateModel(
            name='TestSessionPlanRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.IntegerField()),
                ('semantic_hash', models.CharField(max_length=64)),
                ('planned_start', models.DateTimeField()),
                ('planned_end', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50)),
                ('local_start_intent', models.TextField(blank=True)),
                ('planning_organization_ref', models.UUIDField(blank=True, null=True)),
                ('location_ref', models.UUIDField(blank=True, null=True)),
                ('sport_context_ref', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('REVIEW', 'İncelemede'), ('SCHEDULED', 'Planlandı'), ('LOCKED', 'Kilitli'), ('EXPIRED', 'Zamanı Geçti'), ('CANCELLED', 'İptal Edildi')], default='DRAFT', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField()),
                ('reason', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='planning.testsession')),
            ],
            options={
                'db_table': 'planning_testsessionplanrevision',
                'unique_together': {('session', 'revision_no')},
            },
        ),
        migrations.CreateModel(
            name='TestSessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('athlete_ref', models.UUIDField()),
                ('source_type', models.CharField(choices=[('INDIVIDUAL', 'Bireysel'), ('TEAM', 'Takım'), ('UNIT', 'Birim'), ('PRIOR_SESSION', 'Önceki Oturum'), ('IMPORT', 'İthalat')], max_length=20)),
                ('source_assignment_ref', models.UUIDField(blank=True, null=True)),
                ('source_as_of', models.DateTimeField(blank=True, null=True)),
                ('inclusion_status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('EXCLUDED', 'Hariç'), ('CONDITIONAL', 'Koşullu')], default='PLANNED', max_length=20)),
                ('inclusion_reason_ref', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='planning.testsessionplanrevision')),
            ],
            options={
                'db_table': 'planning_testsessionparticipant',
                'unique_together': {('revision', 'athlete_ref')},
            },
        ),
        migrations.CreateModel(
            name='TestSessionGateEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate_type', models.CharField(choices=[('DEFINITION', 'Tanım'), ('PARTICIPANT', 'Katılımcı'), ('SCIENTIFIC', 'Bilimsel'), ('PRIVACY', 'Gizlilik'), ('GUARDIAN', 'Vasi'), ('HEALTH_SAFETY', 'Sağlık'), ('STAFF', 'Personel'), ('RESOURCE', 'Kaynak'), ('SCHEDULE', 'Takvim')], max_length=30)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('decision_ref', models.UUIDField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('PASS', 'Geçti'), ('WARN', 'Uyarı'), ('FAIL', 'Başarısız'), ('UNKNOWN', 'Bilinmiyor')], max_length=20)),
                ('evaluated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('policy_version', models.CharField(blank=True, max_length=20)),
                ('gatekeeper_role', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_evaluations', to='planning.testsessionplanrevision')),
            ],
            options={
                'db_table': 'planning_testsessiongateevaluation',
            },
        ),
        migrations.CreateModel(
            name='ExecutionHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semantic_hash', models.CharField(max_length=64)),
                ('snapshot_payload', models.JSONField()),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='handoffs', to='planning.testsessionplanrevision')),
            ],
            options={
                'db_table': 'planning_executionhandoff',
            },
        ),
        migrations.CreateModel(
            name='TestSessionResourceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('FACILITY', 'Tesis'), ('DEVICE', 'Cihaz'), ('EQUIPMENT', 'Ekipman'), ('CONSUMABLE', 'Sarf Malzeme')], max_length=20)),
                ('resource_ref', models.UUIDField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('capability_requirement', models.JSONField(blank=True, default=dict)),
                ('reservation_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('ACCEPTED', 'Kabul Edildi'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_requirements', to='planning.testsessionplanrevision')),
            ],
            options={
                'db_table': 'planning_testsessionresourcerequirement',
            },
        ),
        migrations.CreateModel(
            name='TestSessionStaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_ref', models.UUIDField()),
                ('external_snapshot', models.JSONField(blank=True, default=dict)),
                ('role_ref', models.UUIDField()),
                ('qualification_decision_ref', models.UUIDField(blank=True, null=True)),
                ('planned_window_start', models.DateTimeField(blank=True, null=True)),
                ('planned_window_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='planning.testsessionplanrevision')),
            ],
            options={
                'db_table': 'planning_testsessionstaffassignment',
            },
        ),
        migrations.CreateModel(
            name='TestSessionStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station_no', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('facility_ref', models.UUIDField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('planned_window_start', models.DateTimeField(blank=True, null=True)),
                ('planned_window_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='planning.testsessionplanrevision')),
            ],
            options={
                'db_table': 'planning_testsessionstation',
            },
        ),
        migrations.CreateModel(
            name='TestSessionSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('participant_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='planning.testsessionstation')),
            ],
            options={
                'db_table': 'planning_testsessionslot',
            },
        ),
        migrations.CreateModel(
            name='TestSessionTestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_definition_version_ref', models.UUIDField()),
                ('protocol_version_ref', models.UUIDField()),
                ('protocol_assignment_id', models.UUIDField(blank=True, null=True)),
                ('sequence_order', models.IntegerField(blank=True, null=True)),
                ('station_ref', models.UUIDField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='planning.testsessionplanrevision')),
            ],
            options={
                'db_table': 'planning_testsessiontestitem',
            },
        ),
        migrations.CreateModel(
            name='ParticipantTestAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inclusion_status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('EXCLUDED', 'Hariç'), ('CONDITIONAL', 'Koşullu')], default='PLANNED', max_length=20)),
                ('exclusion_reason_ref', models.UUIDField(blank=True, null=True)),
                ('adapted_protocol_assignment_id', models.UUIDField(blank=True, null=True)),
                ('slot_ref', models.UUIDField(blank=True, null=True)),
                ('sequence_override', models.IntegerField(blank=True, null=True)),
                ('gate_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='planning.testsessionparticipant')),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='planning.testsessiontestitem')),
            ],
            options={
                'db_table': 'planning_participanttestassignment',
                'unique_together': {('participant', 'test_item')},
            },
        ),
    ]
