# Generated by Django 6.1 on 2026-09-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsessionplanrevision',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
