# Generated by Django 6.1 on 2026-09-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_testsessionplanrevision_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsessiontestitem',
            name='protocol_version_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
