# Generated by Django 6.1 on 2026-09-02 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.JSONField(verbose_name='Ad (9 dil)')),
                ('description', models.JSONField(verbose_name='Açıklama (9 dil)')),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Erkek'), ('FEMALE', 'Kadın'), ('ALL', 'Tümü')], max_length=20, null=True)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('is_para', models.BooleanField(default=False)),
                ('classification', models.CharField(blank=True, max_length=50)),
                ('source', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_populationdefinition',
            },
        ),
        migrations.CreateModel(
            name='TestProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.JSONField(verbose_name='Ad (9 dil)')),
                ('description', models.JSONField(verbose_name='Açıklama (9 dil)')),
                ('preparation', models.TextField(blank=True)),
                ('execution', models.TextField(blank=True)),
                ('termination', models.TextField(blank=True)),
                ('recording', models.TextField(blank=True)),
                ('equipment_names', models.JSONField(blank=True, default=list)),
                ('equipment_refs', models.JSONField(blank=True, default=list)),
                ('environment', models.TextField(blank=True)),
                ('safety', models.TextField()),
                ('duration_display', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('validity', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ACTIVE', 'Aktif'), ('DEPRECATED', 'Eski'), ('RETIRED', 'Emekli')], db_index=True, default='DRAFT', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_testprotocol',
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_ref', models.UUIDField()),
                ('scope_type', models.CharField(choices=[('METRIC', 'Metrik'), ('TEST', 'Test'), ('PROTOCOL', 'Protokol')], max_length=20)),
                ('scope_ref', models.UUIDField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('RANGE', 'Aralık'), ('LOGICAL', 'Mantıksal'), ('FORMULA_CONSISTENCY', 'Formül Tutarlılığı')], max_length=20)),
                ('parameters', models.JSONField()),
                ('severity', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('ERROR', 'Hata')], default='ERROR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_validationrule',
            },
        ),
        migrations.CreateModel(
            name='NormSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('data_points', models.JSONField(blank=True, default=list)),
                ('summary_stats', models.JSONField()),
                ('lifecycle_status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('DEPRECATED', 'Eski'), ('RETIRED', 'Emekli')], db_index=True, default='ACTIVE', max_length=20)),
                ('source', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_normset',
                'indexes': [models.Index(fields=['lifecycle_status'], name='catalog_nor_lifecyc_79b8ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.JSONField(verbose_name='Ad (9 dil)')),
                ('description', models.JSONField(verbose_name='Açıklama (9 dil)')),
                ('category_ref', models.UUIDField(blank=True, null=True)),
                ('type_ref', models.UUIDField(blank=True, null=True)),
                ('sport_context_refs', models.JSONField(blank=True, default=list)),
                ('purpose', models.TextField(blank=True)),
                ('target_population_refs', models.JSONField(blank=True, default=list)),
                ('target_population_description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('lifecycle_status', models.CharField(choices=[('DRAFT', 'Taslak'), ('REVIEW', 'İncelemede'), ('REJECTED', 'Reddedildi'), ('ACTIVE', 'Aktif'), ('DEPRECATED', 'Eski'), ('RETIRED', 'Emekli'), ('SUPERSEDED', 'Yeni Sürüm')], db_index=True, default='DRAFT', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('successor_test_ref', models.UUIDField(blank=True, null=True)),
                ('source', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_testdefinition',
                'indexes': [models.Index(fields=['lifecycle_status'], name='catalog_tes_lifecyc_50924b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestEvidenceBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_ref', models.UUIDField()),
                ('claim_ref', models.UUIDField(blank=True, null=True)),
                ('applicability', models.TextField(blank=True)),
                ('limitation', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('SUPERSEDED', 'Yeni Kanıt')], default='PENDING', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.testdefinition')),
            ],
            options={
                'db_table': 'catalog_testevidencebinding',
            },
        ),
        migrations.CreateModel(
            name='TestFormulaBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formula_version_id', models.UUIDField()),
                ('input_metrics', models.JSONField()),
                ('output_metric_ref', models.UUIDField()),
                ('applicability', models.TextField(blank=True)),
                ('evidence_ref', models.UUIDField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.testdefinition')),
            ],
            options={
                'db_table': 'catalog_testformulabinding',
            },
        ),
        migrations.CreateModel(
            name='TestMethodBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_version_id', models.UUIDField()),
                ('applicability', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.testdefinition')),
            ],
            options={
                'db_table': 'catalog_testmethodbinding',
            },
        ),
        migrations.CreateModel(
            name='TestMetricBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_version_id', models.UUIDField()),
                ('role', models.CharField(choices=[('PRIMARY', 'Birincil'), ('SECONDARY', 'İkincil'), ('DERIVED', 'Türetilmiş'), ('OPTIONAL', 'Opsiyonel')], default='PRIMARY', max_length=20)),
                ('expected_unit_ref', models.UUIDField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('validation_rules', models.JSONField(blank=True, default=list)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.testdefinition')),
            ],
            options={
                'db_table': 'catalog_testmetricbinding',
            },
        ),
        migrations.CreateModel(
            name='TestNormBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('population_ref', models.UUIDField(blank=True, null=True)),
                ('applicability', models.JSONField(blank=True, default=dict)),
                ('applicability_text', models.TextField(blank=True)),
                ('version', models.IntegerField(default=1)),
                ('lifecycle_status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('DEPRECATED', 'Eski'), ('RETIRED', 'Emekli')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('norm_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.normset')),
                ('test_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.testdefinition')),
            ],
            options={
                'db_table': 'catalog_testnormsbinding',
            },
        ),
        migrations.CreateModel(
            name='PopulationSportContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sportcontext_ref', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.populationdefinition')),
            ],
            options={
                'db_table': 'catalog_population_sportcontext',
                'unique_together': {('population', 'sportcontext_ref')},
            },
        ),
        migrations.CreateModel(
            name='TestProtocolAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter_overrides', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.testdefinition')),
                ('test_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.testprotocol')),
            ],
            options={
                'db_table': 'catalog_testprotocolassignment',
                'unique_together': {('test_definition', 'test_protocol')},
            },
        ),
    ]
