# Generated by Django 6.1 on 2026-09-02 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField()),
                ('execution_id', models.UUIDField()),
                ('participant_id', models.UUIDField()),
                ('formula_binding_id', models.UUIDField()),
                ('input_snapshot', models.JSONField()),
                ('output_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('output_unit', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Başarılı'), ('FAILED', 'Başarısız')], max_length=20)),
                ('error_trace', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'formula_executionlog',
            },
        ),
    ]
