# Generated by Django 6.1 on 2026-09-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaexecutionlog',
            name='execution_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
