# Generated by Django 6.1 on 2026-09-02 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handoff_id', models.UUIDField()),
                ('handoff_hash', models.CharField(max_length=64)),
                ('handoff_expiry', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('IN_PROGRESS', 'Devam Ediyor'), ('PAUSED', 'Durduruldu'), ('COMPLETED', 'Tamamlandı'), ('ABORTED', 'İptal Edildi')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_metadata', models.JSONField(blank=True, default=dict)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('test_items', models.JSONField(blank=True, default=list)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('required_gates', models.JSONField(blank=True, default=dict)),
                ('current_operator_id', models.UUIDField(blank=True, null=True)),
                ('location_actual', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'execution_executionsession',
            },
        ),
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_ref', models.UUIDField()),
                ('test_item_ref', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('IN_PROGRESS', 'Devam Ediyor'), ('COMPLETED', 'Tamamlandı'), ('SKIPPED', 'Atlandı'), ('ABORTED', 'İptal Edildi')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('protocol_ref', models.UUIDField(blank=True, null=True)),
                ('parameter_overrides_used', models.JSONField(blank=True, default=dict)),
                ('adapted_protocol_ref', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='execution.executionsession')),
            ],
            options={
                'db_table': 'execution_executionrun',
            },
        ),
        migrations.CreateModel(
            name='ExecutionDeviation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EXTRA_ATTEMPT', 'Ekstra Deneme'), ('MISSING_PARTICIPANT', 'Eksik Katılımcı'), ('EQUIPMENT_CHANGE', 'Ekipman Değişikliği'), ('ORDER_CHANGE', 'Sıra Değişikliği'), ('PROTOCOL_DEVIATION', 'Protokol Sapması'), ('OTHER', 'Diğer')], max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('CRITICAL', 'Kritik')], max_length=20)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='execution.executionrun')),
                ('execution_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='execution.executionsession')),
            ],
            options={
                'db_table': 'execution_executiondeviation',
            },
        ),
        migrations.CreateModel(
            name='ExecutionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField()),
                ('raw_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('raw_unit_ref', models.UUIDField()),
                ('captured_at', models.DateTimeField()),
                ('operator_id', models.UUIDField()),
                ('device_ref', models.UUIDField(blank=True, null=True)),
                ('device_reading', models.TextField(blank=True)),
                ('calibration_valid_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_best', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('deviation_ref', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='execution.executionrun')),
            ],
            options={
                'db_table': 'execution_executionattempt',
                'unique_together': {('run', 'attempt_number')},
            },
        ),
    ]
