# Generated by Django 6.1 on 2026-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionattempt',
            name='operator_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executionattempt',
            name='raw_unit_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
