# Generated by Django 6.1 on 2026-09-02 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_session_id', models.UUIDField()),
                ('handoff_id', models.UUIDField(unique=True)),
                ('handoff_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('PROCESSING', 'İşleniyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Başarısız'), ('RECALCULATING', 'Yeniden Hesaplanıyor')], db_index=True, default='PENDING', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_results', models.IntegerField(default=0)),
                ('total_derived', models.IntegerField(default=0)),
                ('validation_errors_count', models.IntegerField(default=0)),
                ('processing_log', models.JSONField(blank=True, default=dict)),
                ('is_async', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'measurement_resultbatch',
            },
        ),
        migrations.CreateModel(
            name='MeasurementResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_run_id', models.UUIDField()),
                ('participant_ref', models.UUIDField()),
                ('test_item_ref', models.UUIDField()),
                ('test_definition_ref', models.UUIDField()),
                ('protocol_ref', models.UUIDField()),
                ('metric_ref', models.UUIDField()),
                ('raw_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('raw_unit_ref', models.UUIDField()),
                ('raw_unit_code', models.CharField(blank=True, max_length=50)),
                ('canonical_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('canonical_unit_ref', models.UUIDField()),
                ('canonical_unit_code', models.CharField(blank=True, max_length=50)),
                ('attempt_ref', models.UUIDField(blank=True, null=True)),
                ('operator_id', models.UUIDField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('is_best', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Yayınlandı'), ('RETRACTED', 'Geri Çekildi')], default='PUBLISHED', max_length=20)),
                ('retraction_reason', models.TextField(blank=True)),
                ('conversion_trace', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='measurement.resultbatch')),
            ],
            options={
                'db_table': 'measurement_measurementresult',
                'indexes': [models.Index(fields=['batch', 'participant_ref', 'metric_ref'], name='measurement_batch_i_4ea98d_idx')],
            },
        ),
        migrations.CreateModel(
            name='DerivedMeasurementResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_ref', models.UUIDField()),
                ('test_item_ref', models.UUIDField(blank=True, null=True)),
                ('test_definition_ref', models.UUIDField(blank=True, null=True)),
                ('protocol_ref', models.UUIDField(blank=True, null=True)),
                ('metric_ref', models.UUIDField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_ref', models.UUIDField()),
                ('unit_code', models.CharField(blank=True, max_length=50)),
                ('formula_version_ref', models.UUIDField()),
                ('input_metric_results', models.JSONField(blank=True, default=list)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Yayınlandı'), ('RETRACTED', 'Geri Çekildi')], default='PUBLISHED', max_length=20)),
                ('retraction_reason', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_results', to='measurement.resultbatch')),
            ],
            options={
                'db_table': 'measurement_derivedmeasurementresult',
                'indexes': [models.Index(fields=['batch', 'participant_ref', 'metric_ref'], name='measurement_batch_i_6fea5d_idx')],
            },
        ),
    ]
